# --- Stage 1: Builder ---
FROM node:22-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# --- Stage 2: Nginx Server ---
FROM nginx:alpine AS runner

# Copy the build output from Stage 1 to Nginx's html folder
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]