server {
    # Listen on port 80 inside the container
    listen 80;

    #  matches the COPY command in  Dockerfile
    root /usr/share/nginx/html;
    
    # What file to load first?
    index index.html;

    # Compresses your JS/CSS so it loads faster for users
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # SPA Routing
    # This fixes the "404 Not Found" error when you refresh the page
    location / {
        # First, try to find the actual file (e.g., image.png)
        # If not found, try to find a folder
        # If NEITHER is found, serve index.html (React handles the rest)
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the backend
    location /api {
        proxy_pass http://api-server:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Cache Static Assets (Images, JS, CSS)
    # Tells the browser: "Don't download this again for 1 year"
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Basic Security (Optional)
    # Hides Nginx version number from hackers
    server_tokens off;
}