services:
  # Node Js service for api handling
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api-server-prod
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      # for development, it create live sync for my code without rebuilding
      - ./api-server:/usr/src/app # link .(my current project) to(:) (/usr/src/app) of the container
      # it will ignore the live sync for node_modules
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev

  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker-prod
    restart: unless-stopped
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev

  db:
    image: postgres:16-alpine
    container_name: db-prod
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio-prod
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    command: server /data --console-address ":9001"
    environment:
       MINIO_ROOT_USER: ${MINIO_ROOT_USER}
       MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis-prod
    restart: unless-stopped
    # expose:
    #   - "6379"
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-prod
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - VITE_API_TARGET=http://api-server:3000
    networks:
      - app-network
    depends_on:
      - api-server


volumes:
  postgres-data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge

